services:
    MpStockSync\Services\TrendyolService:
        class: MpStockSync\Services\TrendyolService
        arguments:
            $apiUrl: '%mpstocksync.trendyol.api_url%'
            $sellerId: '%mpstocksync.trendyol.seller_id%'
            $apiKey: '%mpstocksync.trendyol.api_key%'
            $apiSecret: '%mpstocksync.trendyol.api_secret%'
